version: '3.8'

services:
  mic-bot-dev:
    image: mic-bot-node
    container_name: mic-bot-hnsb
    restart: unless-stopped

    volumes:
      - ./src/config.json:/app/dist/config.json:ro
      - ./sessions:/app/sessions

    environment:
      TZ: "Asia/Shanghai"
      NODE_ENV: "production"

    dns:
      - 8.8.8.8
      - 1.1.1.1

    mem_limit: 2g
    cpus: 2
    security_opt:
      - no-new-privileges:true
